---
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
chdir: /var/www/oiga.me/current

address: 127.0.0.1
port: 3562
